##FROM python:3.12

##WORKDIR /app

##COPY requirements requirements.txt
###RUN pip3 install -r requirements.txt

##COPY . .
##EXPOSE 8000
##ENV PYTHONUNBUFFERED="yes"

##ENTRYPOINT ["python3", "app.py"]